<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        p
        {

            font-size: 1.4rem;
            font-weight: 650;
        }
        pre
        {
            color: #fff;
            background-color: #000;
            padding: 1rem;
            border-radius: 10px;
        }
        h1
        {
            text-align: center;
            color: cornflowerblue;
        }
        .code
        {
            border-radius: 10px;
            padding: 1rem 2rem;
            background-color: #d6d5d5;
            margin: 1rem 3rem;
        }
        img
        {
            border-radius: 10px;
        }
    </style>
</head>
<body>9
    <section>
        <!-------home--------->
    </section>
    <section>
        <h1></h1>
        <div class="code">
            <p><b>program 1  </b></p>
            <br>
            <pre>
                
                class Exception
                {
                    public static void main(String[] args)
                    {
                        try {
                            int[] arr = new int[5];
                            
                            arr[10] = 50; // This statement will throw an exception
                
                        } catch (ArrayIndexOutOfBoundsException e) {
                            System.out.println("Exception caught: " + e);
                        }
                    }
                }
                
                
<!-- code -->

            </pre>
            <img src="javapro/javapro/Exception handling/7077ExceptionHandling1.png" alt="">
        </div>



<body>
    body>9
    <section>
        <!-------home--------->
    </section>
    <section>
        <h1></h1>
        <div class="code">
            <p><b>program 2 </b></p>
            <br>
            <pre>
                
               
                class OddNum_Exp {
                    public static void main(String x[]) {
                      int a =4;
                      checknum(a);
                      a =5;
                      checknum(a);
                    }
                  
                    public static void checknum(int a) {
                      try {
                        checkEvenNum(a);
                        System.out.println(a + " is even.");
                      } catch (IllegalArgumentException e) {
                       System.out.println("Exception :" + e.getMessage());
                      }
                    }
                  
                    public static void checkEvenNum(int b) {
                      if (b % 2 != 0) {
                        throw new IllegalArgumentException(b + " is odd.");
                      }
                    }
                  }
<!-- code -->

            </pre>
            <img src="javapro/javapro/Exception handling/7083Exceptionhandling2.png" alt="">
        </div>



<body>body>9
    <section>
        <!-------home--------->
    </section>
    <section>
        <h1></h1>
        <div class="code">
            <p><b>program 3  </b></p>
            <br>
            <pre>
                
                import java.io.File;
                import java.io.FileNotFoundException;
                import java.util.Scanner;
                 
                class Read_File {
                  public static void main(String x[] ) {
                    try {
                      r_File("test2.txt");
                    } catch (FileNotFoundException e) {
                      System.out.println("Exception: " + e.getMessage());
                    }
                  }
                
                  public static void r_File(String fname) throws FileNotFoundException {
                    File file = new File(fname);
                    Scanner scanner = new Scanner(file);
                
                
                    while (scanner.hasNextLine()) {
                      String line = scanner.nextLine();
                      System.out.println(line);
                    }
                
                    scanner.close();
                  }
                }
                
<!-- code -->

            </pre>
            <img src="javapro/javapro/Exception handling/7083Exceptionhandling3.png" alt="">
        </div>



<body>body>9
    <section>
        <!-------home--------->
    </section>
    <section>
        <h1></h1>
        <div class="code">
            <p><b>program 4 </b></p>
            <br>
            <pre>
                
                import java.io.BufferedReader;
                import java.io.File;
                import java.io.FileNotFoundException;
                import java.io.FileReader;
                import java.io.IOException;
                
                class exception4 {
                    class PositiveNumberException extends Exception {
                        public PositiveNumberException(String message) {
                            super(message);
                        }
                    }
                    public static void main(String[] args) {
                        File filename = new File("numbers.txt");
                
                        try {
                            new exception4().checkPositiveNumbers(filename);
                            System.out.println("No positive numbers found.");
                        } catch (PositiveNumberException e) {
                            System.err.println("Exception: " + e.getMessage());
                        } catch (IOException e) {
                            System.err.println("Error reading the file: " + e.getMessage());
                        }
                    }
                
                    void checkPositiveNumbers(File filename) throws IOException, PositiveNumberException {
                        try {
                            BufferedReader reader = new BufferedReader(new FileReader(filename));
                            String line;
                            while ((line = reader.readLine()) != null) {
                                int number = Integer.parseInt(line);
                                if (number > 0) {
                                    throw new exception4.PositiveNumberException("Positive number found: " + number);
                                }
                            }
                            reader.close();
                        } catch (FileNotFoundException e){
                            throw new IOException("The specified file was not found.", e);
                        }
                    }
                }
                
<!-- code -->

            </pre>
            <img src="javapro/javapro/Exception handling/7001Exception4.png" alt="">
        </div>



<body>body>9
    <section>
        <!-------home--------->
    </section>
    <section>
        <h1></h1>
        <div class="code">
            <p><b>program 5 </b></p>
            <br>
            <pre>
                
                // Write a Java program that reads a file and throws an exception if the file is empty.
                import java.io.File;
                import java.io.FileReader;
                import java.io.IOException;
                
                class EmptyFileException extends Exception {
                    public EmptyFileException(String message) {
                        super(message);
                    }
                }
                
                class CheckEmptyFile {
                    public static void main(String[] args) {
                        try {
                            checkFileNotEmpty("data.txt");
                        } catch (EmptyFileException e) {
                            System.out.println("Empty file detected: " + e.getMessage());
                        } catch (IOException e) {
                            System.out.println("File not found or cannot be read: " + e.getMessage());
                        }
                    }
                
                    public static void checkFileNotEmpty(String fileName) throws IOException, EmptyFileException {
                        File file = new File(fileName);
                
                        if (!file.exists() || file.length() == 0) {
                            throw new EmptyFileException("File is empty or does not exist.");
                        }
                
                        FileReader reader = new FileReader(file);
                        reader.close();
                    }
                }
                   
                
<!-- code -->

            </pre>
            <img src="javapro/javapro/Exception handling/7055exceptionHandling5.png" alt="">
        </div>



<body>body>9
    <section>
        <!-------home--------->
    </section>
    <section>
        <h1></h1>
        <div class="code">
            <p><b>program 6  </b></p>
            <br>
            <pre>
                
                class exception6{
                    static class MyException extends Exception{
                        MyException(String msg){
                            super(msg);
                        }
                    }
                
                    public static void main(String arg[]) throws java.io.IOException, exception6.MyException{
                        java.io.BufferedReader input = new java.io.BufferedReader (new java.io.InputStreamReader(System.in));
                        // declare hashmap
                        java.util.HashMap<Integer, Boolean> map = new java.util.HashMap<Integer, Boolean>();
                
                        try{
                            System.out.print("Enter non repeating numbers : ");
                            String[] list = input.readLine().split(" ");
                            
                            for(String st : list){
                                int num = Integer.parseInt(st);
                                if(map.containsKey(num)){
                                    String err = num + " is repeated in the list";
                                    throw new exception6.MyException(err);
                                } else {
                                    map.put(num, true);
                                }
                            }
                            
                        } catch(java.lang.NumberFormatException e){
                            System.out.println("Invalid input. Please enter a valid number.");
                        }
                    }
                }
                
                
<!-- code -->

            </pre>
            <img src="javapro/javapro/Exception handling/" alt="">
        </div>



<body></body>9
    <section>
        <!-------home--------->
    </section>
    <section>
        <h1></h1>
        <div class="code">
            <p><b>program 7  </b></p>
            <br>
            <pre>
                
               
                import java.util.Scanner;

class vowelchecker
{
public static void main(String args[])
{
try
{
Scanner sc = new Scanner(System.in);
System.out.print("Enter a String : ");
String str = sc.nextLine();
checkForVowels(str);
System.out.println("String Contains Vowels.");
}
catch(NoVowelsException e)
{
System.out.println("Exception : "+e.getMessage());
}
}
static void checkForVowels(String input) throws NoVowelsException
{
if(!input.matches(".*[AEIOUaeiou].*"))
{
throw new NoVowelsException("The Input string does not contains any vowels.");
}
}
}
class NoVowelsException extends Exception
{
public NoVowelsException(String message)
{
   super(message);
}
}
<!-- code -->

            </pre>
            <img src="javapro/javapro/Exception handling/7072ExceptionHandling7.png" alt="">
        </div>



<body>body>9
    <section>
        <!-------home--------->
    </section>
    <section>
        <h1></h1>
        <div class="code">
            <p><b>program 8  </b></p>
            <br>
            <pre>
                
               
               
//Write a Java program to connect the Java API to Database, if connection not successful then throw an exception


import java.sql.*;
class ExceptionHandle
{
public static void main(String st[]) 
{
try
{
        Class.forName("com.mysql.jdbc.Driver");
        Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/bharat?useSSL=false","root","god123456");
                System.out.println("Connect to database successfully");
        c.close();

        

        }catch(ClassNotFoundException e){System.out.println("Unable to find class");}
        catch(SQLException e){System.out.println("Fail to connect!");}
        
}
}
                
<!-- code -->

            </pre>
            <img src="javapro/javapro/Exception handling/7101ExceptionHandling8.png" alt="">
        </div>



<body>body>9
    <section>
        <!-------home--------->
    </section>
    <section>
        <h1></h1>
        <div class="code">
            <p><b>program 9  </b></p>
            <br>
            <pre>
                
               
                import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

class DatabaseManager {
    public static void main(String[] args) throws ClassNotFoundException {
//        Class.forName("com.mysql.jdbc.Driver");
        String dbUrl = "jdbc:mysql://localhost:3306/codevengers";
        String username = "root";
        String password = "";

        try {
            Connection connection = new DatabaseManager().getConnection(dbUrl, username, password);
            System.out.println("Connection successfull");
            connection.close();
        } catch (DatabaseConnectionException e) {
            System.out.println("Exception: " + e.getMessage());
        } catch (SQLException e) {
            System.out.println("SQL Exception: " + e.getMessage());
        }
    }

    Connection getConnection(String dbUrl, String username, String password) throws DatabaseConnectionException {
        try {
            return DriverManager.getConnection(dbUrl, username, password);
        } catch (SQLException e) {
            throw new DatabaseConnectionException("Failed to connect to the database: " + e.getMessage());
        }
    }
}

class DatabaseConnectionException extends Exception {
    public DatabaseConnectionException(String message) {
        super(message);
    }
}
<!-- code -->

            </pre>
            <img src="javapro/javapro/Exception handling/7001Exception9.png" alt="">
        </div>



<body>body>9
    <section>
        <!-------home--------->
    </section>
    <section>
        <h1></h1>
        <div class="code">
            <p><b>program 10  </b></p>
            <br>
            <pre>
                
                import java.sql.Connection;
                import java.sql.DriverManager;
                import java.sql.PreparedStatement;
                import java.sql.SQLException;
                
                class DatabaseOperationExample {
                
                    
                    private static final String JDBC_URL = "jdbc:mysql://localhost:3306/your_database_name";
                    private static final String USERNAME = "your_username";
                    private static final String PASSWORD = "your_password";
                
                    public static void main(String[] args) {
                        try {
                          
                            Class.forName("com.mysql.cj.jdbc.Driver");
                
                            
                            try (Connection connection = DriverManager.getConnection(JDBC_URL, USERNAME, PASSWORD)) {
                              
                                if (!insertData(connection, "John Doe", 25, "john@example.com")) {
                                    throw new SQLExceptionCustom("Insert operation failed");
                                }
                
                               
                                if (!updateData(connection, 1, "John Doe Updated")) {
                                    throw new SQLExceptionCustom("Update operation failed");
                                }
                
                               
                                if (!deleteData(connection, 1)) {
                                    throw new SQLExceptionCustom("Delete operation failed");
                                }
                            }
                        } catch (ClassNotFoundException | SQLException | SQLExceptionCustom e) {
                            e.printStackTrace();
                        }
                    }
                
                    
                    private static boolean insertData(Connection connection, String name, int age, String email) throws SQLException {
                        String insertQuery = "INSERT INTO your_table_name (name, age, email) VALUES (?, ?, ?)";
                        try (PreparedStatement preparedStatement = connection.prepareStatement(insertQuery)) {
                            preparedStatement.setString(1, name);
                            preparedStatement.setInt(2, age);
                            preparedStatement.setString(3, email);
                            int rowsAffected = preparedStatement.executeUpdate();
                            return rowsAffected > 0;
                        }
                    }
                
                  
                    private static boolean updateData(Connection connection, int id, String newName) throws SQLException {
                        String updateQuery = "UPDATE your_table_name SET name = ? WHERE id = ?";
                        try (PreparedStatement preparedStatement = connection.prepareStatement(updateQuery)) {
                            preparedStatement.setString(1, newName);
                            preparedStatement.setInt(2, id);
                            int rowsAffected = preparedStatement.executeUpdate();
                            return rowsAffected > 0;
                        }
                    }
                
                    
                    private static boolean deleteData(Connection connection, int id) throws SQLException {
                        String deleteQuery = "DELETE FROM your_table_name WHERE id = ?";
                        try (PreparedStatement preparedStatement = connection.prepareStatement(deleteQuery)) {
                            preparedStatement.setInt(1, id);
                            int rowsAffected = preparedStatement.executeUpdate();
                            return rowsAffected > 0;
                        }
                    }
                }
                
                
                class SQLExceptionCustom extends SQLException {
                    public SQLExceptionCustom(String message) {
                        super(message);
                    }
                }
                
                
                
<!-- code -->

            </pre>
            <img src="javapro/javapro/Exception handling/" alt="">
        </div>







    
</body>
</html>